### ISSUE TITLE
Error when installing the postgresql extension during deployment of the docker container

### ISSUE THREAD

**Issue by seveum** [openswoole/docker-openswoole#44]
docker-compose.yaml
```
services:
    ws:
        container_name: cont_ws
        build:
            context: ./ws
            dockerfile: ./Dockerfile
        environment:
            AUTORELOAD_PROGRAMS: "swoole"
            AUTORELOAD_ANY_FILES: 0
        ports:
            - "9501:9501"
        volumes:
            - ./ws:/var/www
        networks:
            - net_net
```

Dockerfile:
```
FROM openswoole/swoole:25.2-php8.4

RUN \
    install-swoole-ext.sh postgresql
```



```
...
6.196 /usr/src/ext-openswoole/ext-postgresql/openswoole_postgresql.cc:1001:46: error: macro "ZEND_ATOL" passed 2 arguments, but takes just 1
6.196  1001 |                 ZEND_ATOL(long_value, element);
6.196       |                                              ^
6.196 In file included from /usr/local/include/php/Zend/zend_range_check.h:22,
6.196                  from /usr/local/include/php/Zend/zend_portability.h:70,
6.196                  from /usr/local/include/php/Zend/zend_types.h:25,
6.196                  from /usr/local/include/php/Zend/zend.h:27,
6.196                  from /usr/local/include/php/main/php.h:31,
6.196                  from /usr/local/include/php/ext/openswoole/php_openswoole.h:18,
6.196                  from /usr/local/include/php/ext/openswoole/ext-src/php_swoole_private.h:25,
6.196                  from /usr/local/include/php/ext/openswoole/ext-src/php_swoole_cxx.h:19,
6.196                  from /usr/src/ext-openswoole/ext-postgresql/php_swoole_postgresql.h:21,
6.196                  from /usr/src/ext-openswoole/ext-postgresql/openswoole_postgresql.cc:18:
6.196 /usr/local/include/php/Zend/zend_long.h:77: note: macro "ZEND_ATOL" defined here
6.196    77 | #  define ZEND_ATOL(s) atoll((s))
6.196       | 
6.725 /usr/src/ext-openswoole/ext-postgresql/openswoole_postgresql.cc: In function 'void php_pgsql_get_field_value(zval*, PGresult*, zend_long, int, int)':
6.725 /usr/src/ext-openswoole/ext-postgresql/openswoole_postgresql.cc:1001:17: error: 'ZEND_ATOL' was not declared in this scope
6.725  1001 |                 ZEND_ATOL(long_value, element);
6.725       |                 ^~~~~~~~~
[+] Running 0/1 [Makefile:204: openswoole_postgresql.lo] Error 1
 ⠇ Service ws  Building                                                                                                                                                                                                        9.8s 
failed to solve: process "/bin/sh -c install-swoole-ext.sh postgresql" did not complete successfully: exit code: 2

```
